def get_localization(lang, current_user=""):
    """Возвращает словари локализации для интерфейса и блока авторизации."""
    return {
        "Русский": {
            "title": "🔍 Глобальный Аудит QA Анализатор Сайтов",
            "subtitle": f"Многопоточный бизнес-аудит. Личный кабинет: **{current_user}**",
            "history": "📊 Персональная история:",
            "history_empty": "История пуста. Запустите первый глубокий тест!",
            "button": "🚀 Запустить глубокий аудит QA анализа",
            "placeholder_input": "Впишите домен и нажмите Enter (например, habr.com)",
            "warning": "Пожалуйста, укажите адрес сайта!",
            "info": "Инициализация пула задач для: ",
            "spinner": "Движок проверяет ссылки в 20 параллельных потоков...",
            "success": "🎈 Глубокий аудит успешно завершен за {:.2f} сек.",
            "metric_status": "Статус Главной Страницы",
            "metric_links": "Всего ссылок на сайте",
            "table_title": "📊 Карта маршрутизации и валидация статусов (HTTP Health Check):",
            "col_text": "Текст элемента",
            "col_url": "Выходной URL",
            "col_type": "Тип ссылки",
            "col_code": "HTTP Код",
            "col_health": "Здоровье ссылки",
            "download": "📥 Скачать комплаенс-отчет (Excel)",
            "limit_notice": "⚠️ Лимит бесплатного тарифа: Проверено только первые 50 ссылок из {}. Приобретите Premium.",
            "type_int": "Внутренняя",
            "type_ext": "Внешняя",
            "failed": "Ошибка анализа",
            "auth_title": "🔐 Авторизация системы",
            "auth_mode_label": "Выберите действие:",
            "auth_modes": ["Вход", "Регистрация"],
            "login_user": "Логин (имя пользователя):",
            "login_pass": "Пароль:",
            "auth_submit": "Подтвердить",
            "auth_empty_err": "Заполните все поля формы!",
            "auth_login_ok": "Успешный вход в систему!",
            "auth_login_fail": "Неверный логин или пароль!",
            "auth_reg_info": "Теперь переключитесь на вкладку 'Вход'.",
            "logout_btn": "Выйти из системы",
            "status_label": "Вошел как",
            "welcome_info": "👋 Добро пожаловать! Пожалуйста, зарегистрируйтесь или войдите в систему в боковой панели слева, чтобы начать аудит сайтов."
        },
        "English": {
            "title": "🔍 Global Agent QA Website Analyzer",
            "subtitle": f"Multithreaded engine. Logged in as: **{current_user}**",
            "history": "📊 Scan History:",
            "history_empty": "No scans yet. Run your first audit!",
            "button": "🚀 Run Deep Health Audit",
            "placeholder_input": "Enter website and press Enter (e.g. example.com)",
            "warning": "Please enter a valid URL.",
            "info": "Initializing task pool for: ",
            "spinner": "Engine is purging all extracted URLs in 20 parallel threads...",
            "success": "🎈 User AUDIT COMPLETE - processed in {:.2f} seconds.",
            "metric_status": "Main Page Status",
            "metric_links": "Total Links Extracted",
            "table_title": "📊 Routing Map & HTTP Health Status Validation Table:",
            "col_text": "Element Text",
            "col_url": "Target URL",
            "col_type": "Link Type",
            "col_code": "HTTP Code",
            "col_health": "Link Health",
            "download": "📥 Download compliance report (Excel)",
            "limit_notice": "⚠️ Free tier limit: evaluated only first 50 links out of {}. Upgrade to Premium.",
            "type_int": "Internal",
            "type_ext": "External",
            "failed": "Analysis Failed",
            "auth_title": "🔐 System Authentication",
            "auth_mode_label": "Select action:",
            "auth_modes": ["Sign In", "Sign Up"],
            "login_user": "Username:",
            "login_pass": "Password:",
            "auth_submit": "Submit",
            "auth_empty_err": "Please fill in all fields!",
            "auth_login_ok": "Successfully logged in!",
            "auth_login_fail": "Invalid username or password!",
            "auth_reg_info": "Now switch to 'Sign In' tab.",
            "logout_btn": "Sign Out",
            "status_label": "Logged in as",
            "welcome_info": "👋 Welcome! Please register or log in using the sidebar to start auditing websites."
        }
    }[lang]
