def get_localization(lang, current_user):
    """Возвращает словари локализации для интерфейса."""
    return {
        "Русский": {
            "title": "🔍 Глобальный Аудит QA Анализатор Сайтов",
            "subtitle": f"Многопоточный бизнес-аудит. Личный кабинет: **{current_user}**",
            "history": "📊 Персональная история:",
            "history_empty": "История пуста. Запустите первый глубокий тест!",
            "button": "🚀 Запустить глубокий аудит QA анализа",
            "placeholder_input": "Впишите домен и нажмите Enter (например, habr.com)",
            "warning": "Пожалуйста, укажите адрес сайта!",
            "info": "Инициализация пула задач для: ",
            "spinner": "Движок проверяет ссылки в 20 параллельных потоков...",
            "success": "🎈 Глубокий аудит успешно завершен за {:.2f} сек.",
            "metric_status": "Статус Главной Страницы",
            "metric_links": "Всего ссылок на сайте",
            "table_title": "📊 Карта маршрутизации и валидация статусов (HTTP Health Check):",
            "col_text": "Текст элемента",
            "col_url": "Выходной URL",
            "col_type": "Тип ссылки",
            "col_code": "HTTP Код",
            "col_health": "Здоровье ссылки",
            "download": "📥 Скачать комплаенс-отчет (Excel)",
            "limit_notice": "⚠️ Лимит бесплатного тарифа: Проверено только первые 50 ссылок из {}. Приобретите Premium.",
            "type_int": "Внутренняя",
            "type_ext": "Внешняя",
            "failed": "Ошибка анализа"
        },
        "English": {
            "title": "🔍 Global Agent QA Website Analyzer",
            "subtitle": f"Multithreaded engine. Logged in as: **{current_user}**",
            "history": "📊 Scan History:",
            "history_empty": "No scans yet. Run your first audit!",
            "button": "🚀 Run Deep Health Audit",
            "placeholder_input": "Enter website and press Enter (e.g. example.com)",
            "warning": "Please enter a valid URL.",
            "info": "Initializing task pool for: ",
            "spinner": "Engine is purging all extracted URLs in 20 parallel threads...",
            "success": "🎈 User AUDIT COMPLETE - processed in {:.2f} seconds.",
            "metric_status": "Main Page Status",
            "metric_links": "Total Links Extracted",
            "table_title": "📊 Routing Map & HTTP Health Status Validation Table:",
            "col_text": "Element Text",
            "col_url": "Target URL",
            "col_type": "Link Type",
            "col_code": "HTTP Code",
            "col_health": "Link Health",
            "download": "📥 Download compliance report (Excel)",
            "limit_notice": "⚠️ Free tier limit: evaluated only first 50 links out of {}. Upgrade to Premium.",
            "type_int": "Internal",
            "type_ext": "External",
            "failed": "Analysis Failed"
        }
    }[lang]
